name: 'Execução Trabalho Final'
   

on:
  workflow_dispatch:
jobs:
  runs-tests:   
    runs-on: ubuntu-latest
    
    steps: 
      
      - uses: actions/checkout@v4

      
      - uses: actions/setup-node@v4
        with:         
          node-version: 22.x
          
      
      - name: Instalando Yarn
        run: npm install -g yarn
      
      
      - name: Instalando dependências
        run: yarn
      
      
      - name: Instalando Playwright
        run: yarn playwright install

      - name: Instalando as dependencies
        run: npx mocha --version
      
      # executar os testes Trabalho Final
      - name: Executando trabalhoFinal
        run: npx mocha trabalho/trabalho-final.js

     